//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMucBaiViet
    {
        public int DMBVID { get; set; }
        public string TenDMBV { get; set; }
        public string TAGDMBV { get; set; }
    }
}
