//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserWeb
    {
        public int userID { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public string nickName { get; set; }
        public string hoTen { get; set; }
        public Nullable<System.DateTime> ngaySinh { get; set; }
        public string diaChi { get; set; }
        public int thanhVienID { get; set; }
        public string imageName { get; set; }
        public string imagePath { get; set; }
        public Nullable<System.DateTime> ngayDangKy { get; set; }
    
        public virtual ThanhVien ThanhVien { get; set; }
    }
}
